package forthic

Builtin_Word_Proc :: proc(interp: ^Interpreter) -> Error

// Forwards execution of a word to another Interpreter (e.g. a mirror word
// generated by module_mirror), carrying the calling interpreter's stack
// across via a Mirror_Job_Queue.
Mirror_Action :: struct {
  word_name: string,
  target:    ^Interpreter,
  queue:     ^Mirror_Job_Queue,
}

// This is what happens when a Forthic word is executed
Word_Action :: union {
  Builtin_Word_Proc,
  Forthic_Value,
  [dynamic]Compiled_Word,
  Mirror_Action,
}


Word_Doc :: struct {
  stack_effect: string,
  description: string,
  examples: []string,
}

Compiled_Word :: struct {
  name: string,
  action: Word_Action,
  doc: Maybe(Word_Doc),
}

compiled_word_execute :: proc(interp: ^Interpreter, word: Compiled_Word) -> Error {
  switch action in word.action {
  case Builtin_Word_Proc:
    err := action(interp)
    if word.name != "~>" {
      interp.pending_word_options = nil
    }
    return err
  case Forthic_Value:
    stack_push(&interp.stack, action)
    interp.pending_word_options = nil
    return nil
  case [dynamic]Compiled_Word:
    append(&interp.local_frames, map[string]Forthic_Value{})
    defer pop(&interp.local_frames)
    for w in action {
      w_err := compiled_word_execute(interp, w)
      if w_err != nil {
        return w_err
      }
    }
    interp.pending_word_options = nil
  case Mirror_Action:
    job := new(Mirror_Job)
    job.word_name = action.word_name
    job.stack = interp.stack
    interp.stack = Stack{items = make([dynamic]Forthic_Value, 0, interp.default_allocator)}

    mirror_job_queue_push(action.queue, job)
    mirror_job_wait(job)

    interp.stack = job.stack
    err := job.err
    free(job)

    if word.name != "~>" {
      interp.pending_word_options = nil
    }
    return err
  }
  return nil
}

